<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.onlineStore</groupId>
        <artifactId>webParentVer2</artifactId>
        <version>0.0.1-SNAPSHOT</version>

    </parent>
    <groupId>com.onlineStore</groupId>
    <artifactId>WebFrontEndVer2</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>WebFrontEndVer2</name>
    <description>WebFrontEndVer2</description>
    <properties>
        <java.version>19</java.version>
    </properties>
    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.onlineStore</groupId>
            <artifactId>comm</artifactId>
            <version>0.0.2-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.onlineStore</groupId>
            <artifactId>services</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.twilio.sdk/twilio-java-sdk -->
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>frontEnd.FrontEndApplication</mainClass>
                    <skip>false</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
